### ISSUE TITLE
could you please add a node achive convert hexadecimal color values to hue values？

### ISSUE THREAD

**Issue by hexiaoyu946** [Shinsplat/ComfyUI-Shinsplat#4]
Dear developer, I want to convert hexadecimal color values to hue values, please ask if you can add a node to achieve this function, thank you very much！！！
![屏幕截图 2024-06-19 011941](https://github.com/Shinsplat/ComfyUI-Shinsplat/assets/72909117/907da96c-bf01-49a8-b569-d4dcdf50f6dc)

**Comment by Shinsplat** [comment]
Seems to work.

shinsplat_hex_to_other.py
![hex_to_other](https://github.com/Shinsplat/ComfyUI-Shinsplat/assets/90067363/31b1f33a-4bb5-48ef-932c-78b653f25885)

**Comment by hexiaoyu946** [comment]
thank you very much!!

**Comment by Shinsplat** [comment]
You're welcome, my pleasure.
