### ISSUE TITLE
Showing tokens

### ISSUE THREAD

**Issue by Metal-dude** [Shinsplat/ComfyUI-Shinsplat#5]
Great work.

In the workflows, you could add a "show text" node connected to Clip tokens encode, so users could see the token showing up. 

You could also add a [link to the vocabulary](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/raw/main/tokenizer/vocab.json) so users could understand what (320, 1.0), (15329, 1.0), (2759, 1.0) mean, and check that the token analyser is right.

**Comment by jackmeeple** [comment]
For the text output I use someone else's node.

Clip Text Encode (Shinsplat) has a "tokens_out" that displays the token and its associated encoding.  This is also used to pipe into "Clip Tokens Encode (Shinsplat) where the provider "Tensor Toys (Shinsplat)" can be attached, and it contains a "CONDITIONING" output as well as _tokens.
